name: Regenerate the Sitemaps

on:
  repository_dispatch:
    types:
      - resource-published
  workflow_dispatch:

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "Status: ${{ github.event.client_payload.status }}"
          echo "Path: ${{ github.event.client_payload.path }}"
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./tools/sitemap
        run: npm install
      - name: Run scripts and commit changes
        working-directory: ./tools/sitemap
        run: |
          node index.js
          git add ../../sitemap-pages.xml ../../sitemap-tags.xml ../../sitemap-topics.xml
          timestamp=$(date -u)
          git commit -m "Update sitemap files" || exit 0
          git push
