name: Generate the Sitemaps

on:
  schedule:
    # every day at 00:00
    - cron:  '0 0 * * *'
  push:
    branches: 
      - main

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "Checking out git repo"
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./tools/sitemap
        run: npm install
      - name: Install xmllint tool
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils
      - name: Run scripts and commit changes
        working-directory: ./tools/sitemap
        run: |
          node index.js
          git add ../../aemedge/sitemap-news.xml ../../aemedge/sitemap-pages.xml ../../aemedge/sitemap-tags.xml ../../aemedge/sitemap-topics.xml
          timestamp=$(date -u)
          git commit -m "Update sitemap files" || exit 0
          git push
